log_file=log.log
xml_file=/UserApp/src/main/resources/users.xml
keystore_path=C:\\Users\\Bojan\\MDP_Projekat_2024\\UserApp\\src\\main\\resources\\keystore\\keystore.jks
keystore_pass=securemdp
keystore_port=8443
keystore_host=localhost
multicast_port=20000
multicast_host=224.0.0.11
login_fxml=/fxmlPages/LoginPage.fxml
registration_fxml=/fxmlPages/RegistrationPage.fxml
main_window_fxml=/fxmlPages/UserMainWindow.fxml
book_details_fxml=/fxmlPages/BookDetails.fxml
chat_dialog_fxml=/fxmlPages/ChatPage.fxml
suggestions_fxml=/fxmlPages/SuggestionsPage.fxml
salt=sigurnost
login_url=http://localhost:8080/LibraryServer_1/api/users/login
registration_url=http://localhost:8080/LibraryServer_1/api/users/registration
users_url=http://localhost:8080/LibraryServer_1/api/users/getAllUsers
books_url=http://localhost:8080/LibraryServer_1/api/books/getBooks

mail_url=http://localhost:8080/LibraryServer_1/api/mail?mail=
